:custom :
  '(?x-mi:(\R)((?:(?:\R)+(?:\s{4,}|\t).*)+\R)(?=\R))' : "\\1\nΛ auto\\2Λ\n"
  '^!\[(.*?)\]\((.*?)\)$' :  '⚘ \2 \1'
  '!\[(.*?)\]\((.*?)\)' :  '⚓\2 \1⚓'
  '\[(.*?)\]\((.*?)\)' :  '⚓\2 \1⚓'
  '^\s*>' : '〉'
  '^\s*>\s*>' : ' 〉'
  '^\s+\*' : ' •'
  ' {2,}(?=$)' : " ⏎"


:entities :
  :grip :
    :'**' :
      :tag      : :strong
      :marker   : :≡
      :synonyms :
        - :'__'
    :'*' :
      :tag      : :em
      :marker   : :≈
    :'`' : :code
    :'~~' : :del
